# Generated by Django 3.0.8 on 2020-08-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200808_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='static/default.jpg', upload_to='static/profile_pics'),
        ),
    ]
