# Generated by Django 3.0.8 on 2020-08-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200809_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(default=None, upload_to='story_pics'),
        ),
    ]
