# Generated by Django 3.0.8 on 2020-08-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200814_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.TextField(default='uncategorized', max_length=128),
        ),
    ]
