# Generated by Django 3.0.8 on 2020-08-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200814_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.TextField(default='Coding', max_length=128),
        ),
    ]
