# Generated by Django 3.0.8 on 2020-08-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200814_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.TextField(default='uncategorized', max_length=128),
        ),
    ]
