# Generated by Django 3.0.8 on 2020-08-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200814_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, to='news.Category'),
        ),
    ]
