# Generated by Django 3.0.8 on 2020-08-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20200816_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.ForeignKey(default='Story', on_delete=django.db.models.deletion.SET_DEFAULT, to='news.Category'),
        ),
    ]
